#!/bin/bash

cd
echo ""
echo "获取文件管理权限"
termux-setup-storage & sleep 4 &>/dev/null
while true; do
if [ -e storage ]; then
rm -rf /sdcard/box64c
break
else
echo "你必须授权文件管理权限才能进行下一步操作"
fi
sleep 1
done
mkdir -p /sdcard/box64c
pkg clean
pkg update -y
pkg upgrade -y
sleep 2
echo ""
echo "Installing packages"
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install proot -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null
rm -rf $HOME/box64c
mkdir -p $HOME/box64c
cd $HOME/box64c
wget https://github.com/lsl330/box64c/raw/main/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb

echo ""
echo "Downloading preconfigured Rootfs..."
cd $HOME/box64c
wget https://github.com/lsl330/box64c/releases/download/0.0.1-alpha/rootfs.tar.xz

echo ""
echo "Unzipping Rootfs"
tar -xf rootfs.tar.xz
rm -rf rootfs.tar.xz

cd $HOME/box64c/ubuntu-fs/opt
wget https://github.com/lsl330/box64c/raw/main/scripts.tar.gz &>/dev/null
tar -xf scripts.tar.gz
rm -rf scripts.tar.gz

cd $HOME/box64c/
wget -N https://github.com/lsl330/box64c/raw/main/box64c &>/dev/null
chmod +x box64c
mv box64c $PREFIX/bin/
wget -N https://github.com/lsl330/box64c/raw/main/start-proot.sh &>/dev/null
wget -N https://github.com/lsl330/box64c/raw/main/start-chroot.sh &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

rm -rf $HOME/x
. $PREFIX/bin/box64c
