#!/bin/bash

cd
echo ""
echo "Сlick on allow to proceed"
termux-setup-storage & sleep 4 &>/dev/null
while true; do
if [ -e storage ]; then
rm -rf /sdcard/Box64c
break
else
echo "If you denied permission, change it manually in termux app settings now"
fi
sleep 1
done
mkdir -p /sdcard/Box64c
pkg clean
pkg update -y
pkg upgrade -y
sleep 2
echo ""
echo "Installing packages"
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install proot -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null
rm -rf $HOME/Box64c
mkdir -p $HOME/Box64c
cd $HOME/Box64c
wget https://github.com/olegos2/Box64c/raw/main/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb

echo ""
echo "Copying preconfigured Rootfs..."
cd $HOME/Box64c
cp /sdcard/Download/rootfs.tar.xz .

echo ""
echo "Unzipping Rootfs"
tar -xf rootfs.tar.xz
rm -rf rootfs.tar.xz

cd $HOME/Box64c/
cp /sdcard/Download/boxwine . &>/dev/null
chmod +x boxwine
mv boxwine $PREFIX/bin/
cp /sdcard/Download/start-proot.sh . &>/dev/null
cp /sdcard/Download/start-chroot.sh . &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

cd
echo ""
echo "安装完成后，输入'boxwine'启动"

rm -rf $HOME/x
